config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'followers', to: 'users#followers'
  get 'followed', to: 'users#followed'
  get 'search_friend', to: 'users#search'
  get 'search_stock', to: 'stocks#search'
  get 'most_active', to: 'stocks#most_active'
  post 'update_price', to: 'stocks#update_price'
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% object.each do | friend | %>
          <tr>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= friend.email %></td>
            <td>
              <%= link_to 'View profile', user_path(friend), class: 'btn btn-sm btn-success' %>
              <% if local_assigns[:show_unfollow] %>
                <%= link_to 'Unfollow', friendship_path(friend), method: :delete, class: 'btn btn-sm btn-warning', data: {confirm: 'Are you sure?'} %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>