config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'followers', to: 'users#followers'
  get 'followed', to: 'users#followed'
  get 'search_friend', to: 'users#search'
  get 'search_stock', to: 'stocks#search'
  get 'most_active', to: 'stocks#most_active'
  post 'update_price', to: 'stocks#update_price'
end

app/models/stock.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: stock
#
#  created_at :datetime
#  last_price :decimal
#  name       :string(255)
#  ticker     :string(255)
#  updated_at :datetime
#

class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  validates :name, :ticker, presence: true, uniqueness: { case_sensitive: false }
  validates :ticker, length: { maximum: 6 }

  # class methods
  def self.new_lookup(ticker_symbol)
    client = connect_api_client
    begin
      new(name: client.company(ticker_symbol).company_name, ticker: ticker_symbol.upcase, last_price: client.quote(ticker_symbol).latest_price)
    rescue StandardError => e
      puts e
      nil
    end
  end

  def self.most_active_stocks
    client = connect_api_client
    @most_active_stocks = client.stock_market_list(:mostactive)
  end

  def self.check_db(ticker_symbol)
    find_by(ticker: ticker_symbol)
  end

  def self.update_price(stock)
    client = connect_api_client
    price = client.quote(stock.ticker).latest_price
    stock.update(last_price: price)
  end

  def self.connect_api_client
    IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key], endpoint: 'https://sandbox.iexapis.com/v1')
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol to search'
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a symbol to search'
        format.js { render partial: 'users/result' }
      end
    end
  end

  def most_active
    @most_active_stocks = Stock.most_active_stocks
  end

  def update_price
    @user = current_user
    @tracked_stocks = current_user.stocks
    stock = @tracked_stocks.find(params[:id])
    Stock.update_price(stock)
    respond_to do |format|
      format.js { render partial: 'stocks/list' }
    end
  end
end

app/views/stocks/_list.html.erb
<% if @tracked_stocks.any? %>
    <div class="row">
      <div class="col-9">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th scope="col">Ticker</th>
              <th scope="col">Name</th>
              <th scope="col">Price</th>
              <th scope="col">Last update</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
          <% tracked_stocks.each do | stock | %>
              <tr>
                <td><%= stock.ticker %></td>
                <td><%= stock.name %></td>
                <td><%= stock.last_price %></td>
                <td><%=time_ago_in_words(stock.updated_at)%> ago</td>
                <td>
                  <% if current_user.id == user.id %>
                    <%= link_to 'Update', update_price_path(id: stock.id), class: 'btn btn-sm btn-success', method: :post, remote: true %>
                    <%= link_to 'Remove', user_stock_path(stock), method: :delete, class: 'btn btn-sm btn-warning', data: {confirm: 'Are you sure?'} %>
                  <% elsif current_user.can_track_stock?(stock.ticker) %>
                    <%= link_to 'Add to my portfolio', user_stocks_path(user: user, ticker: stock.ticker), class: 'btn btn-success', method: :post %>
                  <% else %>
                    <span class="badge badge-secondary">
                      You are already tracking
                      <% if !user.under_stock_limit? %>
                        10 stocks
                      <% elsif user.stock_already_tracked?(stock.ticker) %>
                        this stock
                      <% end%>
                    </span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    <p class= 'lead'>No tracked stocks yet</p>
  <% end %>

app/views/stocks/_list.js.erb
document.querySelector('#user-stocks').innerHTML = '<%= escape_javascript(render 'stocks/list.html', tracked_stocks: @tracked_stocks, user: @user) %>'

app/views/stocks/most_active.html.erb
<h1>Most active stocks in IEX Finance</h1>

<% if @most_active_stocks.any? %>
  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Symbol</th>
            <th scope="col">Company Name</th>
            <th scope="col">Latest price</th>
            <th scope="col">Latest update</th>
          </tr>
        </thead>
        <tbody>
        <% @most_active_stocks.each do | stock | %>
            <tr>
              <td><%= stock.symbol %></td>
              <td><%= stock.company_name %></td>
              <td><%= stock.latest_price %></td>
              <td><%= stock.latest_time  %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>