config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'followers', to: 'users#followers'
  get 'followed', to: 'users#followed'
  get 'search_friend', to: 'users#search'
  get 'search_stock', to: 'stocks#search'
  get 'most_active', to: 'stocks#most_active'
  post 'update_price', to: 'stocks#update_price'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: stock
#
#  created_at           :datetime
#  email                :string(255),     null: false
#  encrypted_password   :string(255)      default(""), not null
#  first_name           :string(255)
#  last_name            :string(255)
#  updated_at           :datetime
#

class User < ApplicationRecord
  has_many :user_stocks, foreign_key: :user_id, dependent: :destroy
  has_many :stocks, through: :user_stocks
  has_many :active_friendships, class_name: 'Friendship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_friendships, class_name: 'Friendship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followed, through: :active_friendships, source: :followed
  has_many :followers, through: :passive_friendships, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker_symbol)
    stocks.where(ticker: ticker_symbol).any?
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    'Anonymous'
  end

  def following?(friend)
    followed.include?(friend)
  end

  def followed?(friend)
    followers.include?(friend)
  end

  def except_current_user(friend_matches)
    friend_matches.reject { |user| user.id == self.id }
  end

  # class methods
  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back

    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :destroy]

  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def followed
    @followed = current_user.followed
  end

  def followers
    @followers = current_user.followers
  end

  def show
    redirect_to my_portfolio_path if @user == current_user
    @tracked_stocks = @user.stocks
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:friend].present?
      @friend_matches = User.search(params[:friend])
      @friend_matches = current_user.except_current_user(@friend_matches)
      if @friend_matches.any?
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a friend name or email to search'
        format.js { render partial: 'users/friend_result' }
      end
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if friend_matches.any? %>
  <div class="card card-header results-block">
    <table class='table-sm col-md-12'>
      <tbody>
        <% friend_matches.each do | friend | %>
          <tr>
            <td><strong>Full Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td><%= link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-primary' %></td>
            <% if current_user.following?(friend) %>
              <td><span class="badge badge-secondary">
                This user is already followed
              </span></td>
            <% else %>
              <td><%= link_to 'Folllow friend', friendships_path(friend: friend), class: 'btn btn-sm btn-success', method: :post %></td>
            <% end %>
          </tr>
        <% end %>
      <tbody>
    </table>
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'users/friend_result.html', friend_matches: @friend_matches) %>'

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= stock.ticker %>
    <strong>Company: </strong> <%= stock.name %>
    <strong>Price: </strong> <%= stock.last_price %>
    <% if current_user.can_track_stock?(stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), class: 'btn btn-success', method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
           10 stocks
        <% elsif current_user.stock_already_tracked?(stock.ticker) %>
          this stock
        <% end%>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'users/result.html', stock: @stock) %>'

app/views/users/followed.html.erb
<h1>Followed</h1>

<div class="search-area">
  <h3>Search friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: 'Name or email', autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>

<% if @followed.any? %>
  <%= render 'friends/list', object: @followed, show_unfollow: true %>
<% end %>

app/views/users/followers.html.erb
<h1>Followers</h1>

<div id="results">
</div>

<% if @followers.any? %>
  <%= render 'friends/list', object: @followers %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol', autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>

<div id="user-stocks">
  <%= render 'stocks/list', tracked_stocks: @tracked_stocks, user: @user%>
</div>

app/views/users/show.html.erb
<h1>User Details</h1>


<div class="card card-header results-block">
  <table class='table-sm col-md-12'>
    <tbody>
      <tr>
        <td><strong>Full Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <% if current_user.following?(@user) %>
          <td><span class="badge badge-secondary">
            This user is already followed
          </span></td>
        <% else %>
          <td><%= link_to 'Folllow friend', friendships_path(friend: @user), class: 'btn btn-sm btn-success', method: :post %></td>
        <% end %>
      </tr>
    <tbody>
  </table>
</div>

<h3>Stocks tracked by <%= @user.full_name %></h3>
<div id="user-stocks">
  <%= render 'stocks/list', tracked_stocks: @tracked_stocks, user: @user%>
</div>