config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'followers', to: 'users#followers'
  get 'followed', to: 'users#followed'
  get 'search_friend', to: 'users#search'
  get 'search_stock', to: 'stocks#search'
  get 'most_active', to: 'stocks#most_active'
  post 'update_price', to: 'stocks#update_price'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if request.path == most_active_path %>">
            <%= link_to 'Most active stocks', most_active_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Social
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to followed_path, class: 'dropdown-item' do %>
                <%= fa_icon 'user-plus' %> Followed
              <% end %>
              <%= link_to followers_path, class: 'dropdown-item' do %>
                <%= fa_icon 'users' %> Followers
              <% end %>
            </div>
          </li>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path(current_user), class: 'dropdown-item' do %>
                <%= fa_icon 'edit' %> Edit
              <% end %>
              <%= link_to user_path(current_user), class: 'dropdown-item', method: :delete, data: { confirm: 'Are you sure that you want delete your profile? This action is not reversible and your stocks and friends list will be dropped.' } do %>
                <%= fa_icon 'trash' %> Delete
              <% end %>
            </div>
          </li>
        </ul>
        <ul class='navbar-nav ml-auto'>
          <li class='nav-item user-name'>
            <%= fa_icon 'user' %> <span class="badge badge-pill badge-info"><%= current_user.full_name %></span>
          </li>
          <li class='nav-item'>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm logout-button'%>
          </li>
        </ul>
      <% else %>
        <ul class='navbar-nav ml-auto'>
          <li class='nav-item'>
            <%= link_to 'Signup', new_user_registration_path, class: 'btn btn-primary btn-sm logout-button'%>
          </li>
        </ul>
        <ul class='navbar-nav'>
          <li class='nav-item'>
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-success btn-sm logout-button'%>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>